<a href="https://colab.research.google.com/github/ilikeenderman/learning-how-to-use-pytorch/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

In [3]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [4]:
#addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [6]:
#addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [10]:
#subtraciton
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [11]:
#subtraction longhand
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [14]:
#multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [15]:
#multiplication function
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [17]:
#division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [20]:
#div longahnd
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [22]:
#Remainder
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [24]:
#remainder longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [26]:
#Exponents / power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

tensor([ 6,  8, 10, 12])

In [36]:
#Reassignment
tensor_a.add_(tensor_b)


tensor([31, 38, 45, 52])