<a href="https://colab.research.google.com/github/ilikeenderman/learning-how-to-use-pytorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import torch
import numpy as np

In [1]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [11]:
np1 = np.random.rand(3,4)
np1

array([[0.7885203 , 0.27551756, 0.02843085, 0.91650645],
       [0.4130194 , 0.48426958, 0.24944032, 0.61027737],
       [0.33770103, 0.07230306, 0.41810873, 0.69547439]])

In [17]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.1846, -0.5174, -0.8150, -0.2734],
        [ 1.3669,  0.3894,  0.3033,  0.3095],
        [ 0.8281, -0.4772,  1.1609,  1.1001]])

In [20]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [21]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.7885, 0.2755, 0.0284, 0.9165],
        [0.4130, 0.4843, 0.2494, 0.6103],
        [0.3377, 0.0723, 0.4181, 0.6955]], dtype=torch.float64)